version: "3.8"
services:
  api:
    environment:
      - SERVICE_TOKEN=dp.st.dev.UX1vfqhxCCjmjPiwHGVbizAVrOBqmhRAQmcRRJpyN9T
    image: altsports:latest
    container_name: altsports-staging
    expose:
      - "9200"
    ports:
      - "9200:9200"
    restart: "unless-stopped"
