version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gmh7kmain
    ports:
      - "5432:5432"
    volumes:
      - altsports-db:/var/lib/postgresql/data

volumes:
  altsports-db:
